var Name = "Wessel van Arkel";
console.log("Name: " + Name);
var Age = 16
console.log("Age: " + Age)
var Jumpforce = 20;
console.log("Jumpforce: " + Jumpforce);
var Strength = 120
console.log("Strenght: " + Strength);
var Speed = 280 
console.log("Speed: " + Speed);
var Lives = 1
console.log("Lives: " + Lives);
var Level = 1249
console.log("Level: " + Level);
var Ammo = 127
console.log("Ammo: " + Ammo);
var Wanted = "True"
console.log("Wanted: " + Wanted)
var Money = 929320
console.log("Money: " + Money)